import * as fs from "node:fs";
import * as path from "node:path";

interface ProjectInfo {
  name: string;
  type: "module" | "ui-app" | "unknown";
  interface: "universal" | "legacy" | "none";
  description: string;
  dependencies: string[];
}

function detectProject(projectDir: string): ProjectInfo {
  const info: ProjectInfo = {
    name: "unknown",
    type: "unknown",
    interface: "none",
    description: "",
    dependencies: [],
  };

  const metadataPath = path.join(projectDir, "metadata.json");
  if (fs.existsSync(metadataPath)) {
    const metadata = JSON.parse(fs.readFileSync(metadataPath, "utf-8"));
    info.name = metadata.name || "unknown";
    info.type = metadata.type === "ui" ? "ui-app" : "module";
    info.interface = metadata.interface === "universal" ? "universal" : "legacy";
    info.description = metadata.description || "";
    info.dependencies = metadata.dependencies || [];
  }

  return info;
}

function loadGuidelines(boostDir: string): string {
  const guidelinesDir = path.join(boostDir, "guidelines");
  if (!fs.existsSync(guidelinesDir)) return "";

  const files = fs.readdirSync(guidelinesDir).filter((f) => f.endsWith(".md")).sort();
  const sections: string[] = [];

  for (const file of files) {
    const content = fs.readFileSync(path.join(guidelinesDir, file), "utf-8");
    sections.push(content.trim());
  }

  return sections.join("\n\n---\n\n");
}

function generateAgentsMd(projectDir: string, boostDir: string): string {
  const project = detectProject(projectDir);
  const guidelines = loadGuidelines(boostDir);

  const lines: string[] = [];

  lines.push("# Logos Development Context");
  lines.push("");
  lines.push("> This file is generated by logos-dev-boost. It provides AI coding agents with");
  lines.push("> accurate context about the Logos modular application platform.");
  lines.push("> Do not edit the section between BEGIN and END markers.");
  lines.push("");

  if (project.name !== "unknown") {
    lines.push("## This Project");
    lines.push("");
    lines.push(`- **Name:** ${project.name}`);
    lines.push(`- **Type:** ${project.type === "ui-app" ? "UI App (Basecamp plugin)" : "Logos Module (core)"}`);
    if (project.interface === "universal") {
      lines.push("- **Interface:** Universal (pure C++ impl, generated Qt glue)");
    }
    if (project.description) {
      lines.push(`- **Description:** ${project.description}`);
    }
    if (project.dependencies.length > 0) {
      lines.push(`- **Dependencies:** ${project.dependencies.join(", ")}`);
    }
    lines.push("");
  }

  lines.push("<!-- BEGIN:logos-dev-boost -->");
  lines.push("");

  if (guidelines) {
    lines.push("## Logos Development Guidelines");
    lines.push("");
    lines.push(guidelines);
    lines.push("");
  }

  lines.push("## Quick Reference");
  lines.push("");
  lines.push("### Build Commands");
  lines.push("");
  lines.push("```bash");
  lines.push("nix build                    # Build the module/app");
  lines.push("nix build -L                 # Build with streaming logs");
  lines.push("nix flake check -L           # Run tests");
  lines.push("nix develop                  # Enter dev shell");
  lines.push("```");
  lines.push("");

  if (project.interface === "universal") {
    lines.push("### Universal Module Build Pipeline");
    lines.push("");
    lines.push("This is a universal C++ module. The build pipeline is:");
    lines.push("1. `preConfigure` in flake.nix runs `logos-cpp-generator --from-header`");
    lines.push("2. Generator reads the pure C++ impl header and metadata.json");
    lines.push("3. Generator produces `generated_code/*_qt_glue.h` and `*_dispatch.cpp`");
    lines.push("4. CMake compiles everything into a Qt plugin `.so`/`.dylib`");
    lines.push("");
    lines.push("Your code is pure C++ (std::string, int64_t, etc). The generator handles all Qt types.");
    lines.push("");
  }

  lines.push("### Testing");
  lines.push("");
  lines.push("```bash");
  lines.push("# Integration test with logoscore");
  if (project.name !== "unknown") {
    lines.push(`logoscore -m ./result/lib -l ${project.name} -c "${project.name}.methodName(args)"`);
  } else {
    lines.push('logoscore -m ./result/lib -l <module> -c "<module>.methodName(args)"');
  }
  lines.push("");
  lines.push("# Inspect module metadata and methods");
  if (project.name !== "unknown") {
    lines.push(`lm ./result/lib/${project.name}_plugin.so`);
    lines.push(`lm methods ./result/lib/${project.name}_plugin.so --json`);
  } else {
    lines.push("lm ./result/lib/<name>_plugin.so");
    lines.push("lm methods ./result/lib/<name>_plugin.so --json");
  }
  lines.push("```");
  lines.push("");

  lines.push("### Packaging");
  lines.push("");
  lines.push("```bash");
  if (project.name !== "unknown") {
    lines.push(`lgx create ${project.name}`);
    lines.push(`lgx add ${project.name}.lgx -v linux-x86_64 -f ./result/lib/${project.name}_plugin.so`);
    lines.push(`lgx verify ${project.name}.lgx`);
  } else {
    lines.push("lgx create <name>");
    lines.push("lgx add <name>.lgx -v linux-x86_64 -f ./result/lib/<name>_plugin.so");
    lines.push("lgx verify <name>.lgx");
  }
  lines.push("```");
  lines.push("");

  lines.push("### For detailed documentation, see the logos-dev-boost docs/ directory");
  lines.push("### or activate a skill: create-universal-module, wrap-external-lib,");
  lines.push("### create-ui-app, package-lgx, inter-module-comm, testing-modules,");
  lines.push("### nix-flake-setup, add-to-workspace");
  lines.push("");
  lines.push("<!-- END:logos-dev-boost -->");

  return lines.join("\n");
}

const projectDir = process.argv[2] || process.cwd();
const boostDir = process.argv[3] || path.resolve(import.meta.dirname, "..", "..");

const content = generateAgentsMd(projectDir, boostDir);
const outputPath = path.join(projectDir, "AGENTS.md");
fs.writeFileSync(outputPath, content);
console.log(`Generated ${outputPath}`);
